############################################
## Starship: Theme => default
## version 1.1
############################################

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# A continuation prompt that displays two filled in arrows
continuation_prompt = "[∙](bright-blue) "

# Timeout for commands executed by starship (in milliseconds). Default: 500.
# command_timeout = 500

# A minimal left prompt
# format = """$directory\
# $git_branch\
# $git_status
# $character"""

format = """
[$time$memory_usage$jobs$directory$git_branch$git_status](bold dimmed purple)
$sudo$character"""

# move the rest of the prompt to the right
right_format = """[$cmd_duration$vagrant$docker_context$php$lua$battery$status](bold dimmed purple)"""

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "
format = '\[[$symbol$percentage]($style)\]'

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 25
style = "bold red"

[[battery.display]] # "bold yellow" style and 💦 symbol when capacity is between 10% and 30%
threshold = 50
style = "yellow"
discharging_symbol = "💦"

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 75
style = "green"
# when capacity is over 30%, the battery indicator will not be displayed

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)[➜](bold blue)"

[cmd_duration]
min_time = 2000
format = '\[[⏱ $duration]($style)\]'
# @since 1.1 notifications
show_notifications = true
min_time_to_notify = 60000

[directory]
style = "cyan"
# truncate_to_repo = false
truncation_symbol = "…/"
# truncation_length = 3
home_symbol = "🏠"
format = '(\[[$path]($style)[$read_only]($read_only_style)\])'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[env_var.SIUID]
style = "purple"
format = '\[[$env_value]($style)\]'
default = "unknown user"

[git_branch]
symbol = ""
format = '\[[$symbol$branch]($style)\]'

[git_status]
# @since 1.1 disabled
disabled = true
format = '([\[$all_status$ahead_behind\]]($style))'

[line_break]
disabled = false

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
disabled = false
# threshold = -1
threshold = 70
# symbol = " "
style = "bold dimmed green"
format = '\[$symbol[[$ram_pct](bold dimmed blue)([|](dimmed red)[$swap_pct](bold dimmed yellow))]($style)\]'

[package]
disabled = true

[php]
version_format = "v${raw}"
symbol = "🐘"
format = '\[[$symbol($version)]($style)\]'

[shell]
disabled = false
format = '\[[$indicator]($style)\]'

[status]
disabled = false
format = '\[[$symbol$status]($style)\]'

[sudo]
disabled = false
style = 'bold green'
symbol = '🫆 '
# symbol = '👩‍💻 '

[time]
disabled = false
# style = "bold dimmed blue"
style = "blue"
format = '\[[$time]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'
